Fix requirements.txt
Remove extraneous comma which led to
```
error: Couldn't parse requirement in `requirements.txt` at position 339
  Caused by: Unexpected end of version specifier, expected operator
ruff==0.11.6,
             ^
```